### ISSUE TITLE
Cannot generate code Cannot connect to the backend

### ISSUE THREAD

**Issue by psy-mas** [sirily11/SECYAN-GEN#10]
Hi, thanks for making such an awesome library.

However, I encounter some troubles while testing it out. When I was trying to run a query from Query Editor, and It showed **“Cannot generate code Cannot connect to the backend”**

I've followed the docker installing instruction to compose up all the three containers needed in a Centos 7.8 server, including import data into the tpch-database.

When I was trying to run a query from Query Editor, and It showed **“Cannot generate code Cannot connect to the backend”**,

**The Raw Data Configuration was：**
'''
[
    {
        "annotations": [
            "CAST(c_mktsegment = 'AUTOMOBILE' AS int)"
        ],
        "columns": [
            {
                "column_type": "INT",
                "name": "n_nationkey"
            },
            {
                "column_type": "STRING",
                "name": "n_name"
            },
            {
                "column_type": "INT",
                "name": "n_regionkey"
            },
            {
                "column_type": "STRING",
                "name": "n_comment"
            }
        ],
        "data_paths": [
            "/usr/local/project/output_dir/nation.tbl"
        ],
        "data_sizes": [
            25
        ],
        "table_name": "nation",
        "owner": "SERVER"
    }
]
'''
**and the query was ：**
'''
SELECT *  FROM nation;
'''
Any suggestions? Looking foward for your replying.

Once again, thanks for making such an awesome library!!!

**Comment by sirily11** [comment]
Yeah. I will take a look at it and  will fix this example bug in the next release. Stay around! Thx for your bug report!
